[main.build]
  transpiler = "dartsass"
  silenceDeprecations = true

[favicon]
    logo = "image/wmoc2027_logo.png"
    sizes = [16, 32, 48]

[head]
    tagline = "Top"

[navigation]
    anchor = true
    logo = "/image/wmoc2027_logo.png"
    logo-height = 100
    color = "body"
    fixed = false
    overlay = false
    overlayMode = "dark"
    horizontal = false
    offset = "5.5rem"
    search = true
    searchModal = true
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"
    [navigation.padding]
        x = 4
        y = 4

[messages]
    placement = "bottom-right"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

    [[sharing.providers]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
        icon = "fab linkedin"
        weight = 10

    [[sharing.providers]]
        name = "x"
        url = "https://twitter.com/home?status={url}"
        icon = "fab x-twitter"
        weight = 20

    [[sharing.providers]]
        name = "Facebook"
        url = "https://www.facebook.com/sharer.php?u={url}"
        icon = "fab facebook"
        weight = 30

    [[sharing.providers]]
        name = "WhatsApp"
        url = "whatsapp://send?text={title}%20{url}"
        icon = "fab whatsapp"
        weight = 40

    [[sharing.providers]]
        name = "email"
        url = "mailto:contact@wmoc2027.jp"
        icon = "fas link"
        weight = 50
        clipboard = true

[modules.hinode.csp]
    frame-src = [
        "https:",                        # Allow all HTTPS sources
        "wmoc2027.jp",                   # Specific domain
        "*.googletagmanager.com",
        "player.cloudinary.com",
        "www.youtube-nocookie.com",
        "www.youtube.com",
        "player.vimeo.com"
    ]