disabled = false
languageCode = "en"
languageName = "English"
contentDir = 'content/en'
weight = 1

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"

  [params.head]
    tagline = "WMOC2027"
  [params.social]
    title = "Contact"
    caption = "To get to know us better, feel free to reach out or follow us on social media."
  [params.footer]
    # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer nofollow'>CC BY-NC-SA 4.0</a>)."
    # toml-docs-end lang-param
  [params.sections.blog]
    reference = "More Posts"
  [params.sections.projects]
    reference = "More Projects"