disabled = false
languageCode = "ja"
languageName = "日本語"
contentDir = 'content/ja'
weight = 1

[params]
  displayName = "JA"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006 2 1"
  [params.social]
    title = "お問い合わせ"
    caption = "ご質問などはこちらへお問い合わせください。またSNSでは最新情報や日々の活動をお届けしています。"
  [params.footer]
    # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer nofollow'>CC BY-NC-SA 4.0</a>)."
    # toml-docs-end lang-param
  [params.sections.blog]
    reference = "More Posts"
  [params.sections.projects]
    reference = "More Projects"
